name: Publish

on:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  publish-go:
    name: GoReleaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.24.3

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.NITRIC_BOT_TOKEN }}

  publish-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.NITRIC_BOT_TOKEN }}

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Git Identity
        run: |
          git config --global user.name 'nitric-bot[bot]'
          git config --global user.email 'maintainers@nitric.io'

      - name: Set Version
        # Tag will already be created by release flow
        run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish latest to NPM
        if: "!github.event.release.prerelease"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish latest RC to NPM
        if: "github.event.release.prerelease"
        run: npm publish --access public --tag rc-latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
